User can view items for sale.
stephyacek/Online-Store pull request #7
Opened 2017-06-13 22:54 UTC by stephyacek

<img width="1407" alt="screen shot 2017-06-13 at 3 51 58 pm" src="https://user-images.githubusercontent.com/29046195/27108121-6386c3d2-5050-11e7-9fa5-891d1fdf469e.png">
<img width="1302" alt="screen shot 2017-06-13 at 3 52 49 pm" src="https://user-images.githubusercontent.com/29046195/27108125-66afdbe8-5050-11e7-99d3-f603fe1ccaa2.png">

2017-06-13 23:20 UTC, ronperris requested changes
Please move the art into an array in JavaScript and draw the list dynamically.

2017-06-14 19:42 UTC, ronperris commented on main.js
> +var product = [
I think this should be products, plural.

2017-06-14 19:43 UTC, ronperris commented on main.js
> +  { image: 'images/photo1.jpg',
These names should either be descriptions of the images or have a hyphen between image and the number.

2017-06-14 19:44 UTC, ronperris commented on main.js
> +  { image: 'images/photo2.jpg',
The starting { should be on a separate line from the image property.

2017-06-14 19:44 UTC, ronperris commented on main.js
> +var $artworkSection = document.querySelector('.artwork')
Could this just be called $artwork?

2017-06-14 19:45 UTC, ronperris commented on main.js
> +document.addEventListener('DOMContentLoaded', renderPhotos(product))
You are calling renderPhotos here, did you actually want to pass it to the event listener instead?

2017-06-14 19:46 UTC, ronperris commented on main.js
> +  var $span = document.createElement('span')
Would $product be a better name? Then you don't need it in all the other variable's names.

2017-06-14 19:53 UTC, ronperris commented on main.js
> +function renderPhotos(product) {
This parameter should be products, it is a collection of more than on product.

2017-06-14 19:53 UTC, ronperris commented on main.js
> +    var eachProduct = createEachProduct(product[i])
This should be $product, it is an element.

2017-06-14 19:54 UTC, ronperris commented on styles.css
> +  max-width: 35px;
Could this be in rem? Like the rest of the values your using for spacing.

2017-06-14 19:54 UTC, stephyacek commented on main.js
> +  { image: 'images/photo1.jpg',
So renaming my saved images "photo-1", "photo-2" etc?

2017-06-14 19:55 UTC, ronperris commented on styles.css
> +  font-weight: lighter;
This is using lighter and above your using 600. Make them consistent.

2017-06-14 19:56 UTC, ronperris requested changes
Please fix the issues, check the inline comments for details.

2017-06-14 23:26 UTC, ronperris approved these changes

2017-06-14 23:26 UTC, ronperris approved these changes
Looks good to merge.

2017-06-14 23:26 UTC, merged